### PR TITLE
Minor obvious fixes and stuff for MySQL 5.7

### PR DESCRIPTION
**Pull request by nicholi**
On checkout the app won't run. Just some minor mistakes likes missing async require and incorrectly pulling config.json. Minor additons such as env var for DB_PORT and removed the generated templates.js file (as well as added to .gitignore).

The other fixes are related to MySQL 5.7 and its new defaults, which are really only forcing people to write better SQL queries. New version sets sql_mode STRICT_TRANS_TABLES (affects the default value of timestamps, they MUST be set and can't be zero) and ONLY_FULL_GROUP_BY (gets angry about sloppy queries with GROUP BY).

The STRICT_TRANS_TABLES pretty much blocks any of the tables from being created that do NOT have a default value for a `timestamp` field. So I modified those db-migration files to just default to CURRENT_TIMESTAMP.

As I was clicking through the UI of the app, I found the inventory groups, types, and market groups threw some errors because of the GROUP BY clause. Made a new db-migration file for that, which just requires hinting to sql that the name field should actually be unique (and it can't be null).

### CODE REVIEW

**Comment by happilymarrieddad** [comment]
@Nicholi hey man I will pull if you're still interested. This is pretty old anyways. I was thinking of building an actual live market watcher with email/sms alerts but I haven't gotten around to it yet.

**Comment by nicholi** [comment]
Yeah I was actually just separating them into plain fixes and mysql57 fixes. Also I found the name's aren't unique, so my fix was technically incorrect.

**Comment by happilymarrieddad** [comment]
@Nicholi hey man I just merged your requests. Thanks for the awesome job!

**Comment by nicholi** [comment]
You too, in case someone finds those YouTube Guides 😀

On Jul 17, 2017 2:51 PM, "Nick Kotenberg" <notifications@github.com> wrote:

@Nicholi <https://github.com/nicholi> hey man I just merged your requests.
Thanks for the awesome job!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/happilymarrieddad/eve-app/pull/1#issuecomment-315895925>,
or mute the thread

**Pull request closed without merging**
